api_version = "2025-04"

[[extensions]]
name = "Returns - Request Form"
handle = "returns-request-form"
uid = "dcac3620-09d6-7dad-6b72-330ee19e432903ac2149"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/MenuItemAction.tsx"
target = "customer-account.order.action.menu-item.render"

[[extensions.targeting]]
module = "./src/TestAction.tsx"
target = "customer-account.order.action.render"

[[extensions.targeting]]
module = "./src/ReturnBlock.tsx"
target = "customer-account.order-status.cart-line-list.render-after"
